Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/openjdk-jdk-8-centos7"

    test01.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
